// <auto-generated />
namespace HotelGlob.RMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SmallChanges2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SmallChanges2));
        
        string IMigrationMetadata.Id
        {
            get { return "201709181523268_SmallChanges2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
